**Import Libraries**

In [2]:
import pandas as pd
import numpy as np

**Load Dataset**

In [10]:
# Load dataset
df = pd.read_excel('/Dataset for Data Analytics.xlsx')

**Explore Dataset**

In [9]:
# Show first 5 rows
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

**CHECK DATASET INFORMATION**

In [11]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

**CHECK TOTAL ROWS & COLUMNS**

In [12]:
print("Rows and Columns:", df.shape)

Rows and Columns: (1200, 14)

**CHECK COLUMN NAMES**

In [13]:
print(df.columns)

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

**CHECK MISSING VALUES**

In [14]:
# Check missing values
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

**HANDLE MISSING VALUES**

In [15]:
# Replace missing CouponCode values
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

**VERIFY MISSING VALUES AGAIN**

In [16]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

**CHECK DUPLICATE ROWS**

In [17]:
# Check duplicate rows
duplicates = df.duplicated().sum()
print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

**REMOVE DUPLICATES (IF ANY)**

In [18]:
# Remove duplicate rows
df = df.drop_duplicates()

**CHECK DUPLICATE ORDER IDs**

In [19]:
# Check duplicate OrderIDs
duplicate_ids = df['OrderID'].duplicated().sum()
print("Duplicate OrderIDs:", duplicate_ids)

Duplicate OrderIDs: 0

**CHECK DATE FORMAT**

In [20]:
# Convert Date column to proper datetime format
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

**CHECK INVALID DATES**

In [21]:
# Check invalid dates
invalid_dates = df['Date'].isnull().sum()

print("Invalid Dates:", invalid_dates)

Invalid Dates: 0

**FORMAT DATE COLUMN**

In [22]:
# Standardize date format
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

**CHECK DATA TYPES**

In [23]:
print(df.dtypes)

OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

**CLEAN TEXT COLUMNS**

In [24]:
# Remove extra spaces from text columns
text_columns = [
    'Product',
    'ShippingAddress',
    'PaymentMethod',
    'OrderStatus',
    'CouponCode',
    'ReferralSource'
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

**STANDARDIZE TEXT FORMAT**

In [25]:
# Capitalize text properly
df['PaymentMethod'] = df['PaymentMethod'].str.title()
df['OrderStatus'] = df['OrderStatus'].str.title()
df['ReferralSource'] = df['ReferralSource'].str.title()

**VALIDATE TOTAL PRICE**

In [26]:
# Create validation column
df['PriceCheck'] = np.where(
    df['Quantity'] * df['UnitPrice'] == df['TotalPrice'],
    'Correct',
    'Mismatch'
)

**FINAL QUALITY CHECK**

In [28]:
print("FINAL PROJECT CHECK")

print("---------------------------")

print("Missing Values:")
print(df.isnull().sum())

print("---------------------------")

print("Duplicate Rows:", df.duplicated().sum())

print("---------------------------")

print("Duplicate OrderIDs:",
      df['OrderID'].duplicated().sum())

print("---------------------------")

print("Invalid Dates:",
      df['Date'].isnull().sum())

FINAL PROJECT CHECK
---------------------------
Missing Values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
PriceCheck         0
dtype: int64
---------------------------
Duplicate Rows: 0
---------------------------
Duplicate OrderIDs: 0
---------------------------
Invalid Dates: 0

**DOWNLOAD CLEANED FILE**

In [29]:
# Save cleaned dataset
df.to_excel('Project1_Cleaned_Dataset.xlsx', index=False)
print("Cleaned dataset saved successfully!")
from google.colab import files
files.download('Project1_Cleaned_Dataset.xlsx')

Cleaned dataset saved successfully!

**(GENERATE PROJECT REPORT)**

In [30]:
report = """
DATA ANALYTICS PROJECT 1 REPORT

Objective:
Clean and prepare raw dataset.

Tasks Performed:
1. Handled missing values
2. Checked duplicate rows
3. Verified duplicate OrderIDs
4. Corrected date formatting
5. Standardized text formatting
6. Validated TotalPrice calculations

Final Results:
- Missing values handled
- Duplicate rows: 0
- Duplicate OrderIDs: 0
- Invalid dates: 0

Project completed successfully.
"""

with open("Project_Report.txt", "w") as file:
    file.write(report)

print("Project report created!")

Project report created!

**DOWNLOAD REPORT**

In [31]:
files.download('Project_Report.txt')